packages:
  - 'packages/*'

catalog:
  "@types/node": "^25.9.3"
  "minisearch": "^7.2.0"
  "unified": "^11.0.5"
  "remark-parse": "^11.0.0"
  "remark-rehype": "^11.1.2"
  "rehype-stringify": "^10.0.1"
  "@shikijs/rehype": "^4.2.0"
  "shiki": "^4.2.0"
  "rehype-slug": "^6.0.0"
  "remark-gfm": "^4.0.0"
  "remark-frontmatter": "^5.0.0"
  "typescript": "^5.8.3"
